Vagrant.configure("2") do |config|
  # config.vm.define :servidorUbuntu do |servidorUbuntu|
  # servidorUbuntu.vm.box = "bento/ubuntu-20.04"
  # servidorUbuntu.vm.network :private_network, ip: "192.168.100.3"
  # servidorUbuntu.vm.hostname = "servidorUbuntu"
  # servidorUbuntu.vm.provision :shell, path: "boot.sh"
  # #servidorUbuntu.vm.network :forwarded_port, guest: 80, host:5000
  # # servidorUbuntu.vm.synced_folder "./directorio", "/home/vagrant/directorio", type:"virtualbox"
  # end
  config.vm.define :server do |server|
  server.vm.box = "bento/ubuntu-20.04"
  server.vm.network :private_network, ip: "192.168.100.2"
  server.vm.hostname = "server"
  server.vm.provision :shell, path: "bootstrap.sh"
  end
  config.vm.define :ubuntu do |ubuntu|
  ubuntu.vm.box = "bento/ubuntu-20.04"
  ubuntu.vm.network :private_network, ip: "192.168.100.3"
  ubuntu.vm.hostname = "ubuntu"
  ubuntu.vm.provision :shell, path: "boot2.sh"
  end
  config.vm.define :ubuntu2 do |ubuntu2|
  ubuntu2.vm.box = "bento/ubuntu-20.04"
  ubuntu2.vm.network :private_network, ip: "192.168.100.4"
  ubuntu2.vm.hostname = "ubuntu2"
  ubuntu2.vm.provision :shell, path: "boot.sh"
  end
  end